parameters:
    oxpecker.data.process.class: Cifren\OxPeckerData\Core\DataProcess

services:
    oxpecker.data.process:
        class:      %oxpecker.data.process.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@logger"
