sudo: false
language:
    - php

services:
    - docker

before_install:
    - docker pull composer:latest

before_script:
    #coverage needs xdebug
    #- phpenv config-rm xdebug.ini
    - composer install
  
script:
    - php bin/php-cs-fixer fix -v --diff --dry-run
    - php bin/phpunit
    
notifications:
    email:
        -  cifren@msn.com